baseURL = "http://yuriwong.github.io/blog/public/"
languageCode = "en-us"
title = "My Blog"
theme = "vienna"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright hyyu"

[params]
    # Social accounts. Link to these accounts are displayed in the header and
    # footer.
    twitter = "Your Twitter username"
    github = "Your GitHub username"
    linkedin = "Your LinkedIn username"
    facebook = "Your Facebook username"
    reddit = "Your Reddit username"
    hackernews = "Your Hacker News username"
    stackoverflow = "Your Stackoverflow user id (number)"
    # Disqus shortname
    disqus = "Your disqus shortname"
    # Google Analytics API key.
    ga_api_key = "Your Google Analytics tracking id"
    # Mixpanel API key.
    mixpanel_api_key = "Your Mixpanel API key"
    author = "Hyyu"
    avatar = "/path/to/avatar"
    contact = "yuriwong002@gmail.com(mailto:yuriwong002@gmail.com)"
    bio = "Your short bio"
    # Short subtitle/tagline. This is displayed in the header.
    subtitle = "tagline of your blog"
    themecolor = "#hexcolor" # Defines the tab color in Chrome for Android.
